src/main/java/org/gab/estimateachers/entities/client/Card.java
package org.gab.estimateachers.entities.client;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.gab.estimateachers.entities.system.discussions.Discussion;
import org.gab.estimateachers.entities.system.users.User;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

@NoArgsConstructor
@MappedSuperclass
@Getter
@Setter
public abstract class Card {
    
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    protected Long id;
    
    @Column(
            name = "title",
            nullable = false
    )
    protected String title;
    
    @Column(
            name = "card_type",
            nullable = false
    )
    @Enumerated(EnumType.STRING)
    protected CardType cardType;
    
    @Column(
            name = "approved",
            columnDefinition = "boolean default 'f'"
    )
    protected Boolean approved;
    
    @ElementCollection(
            targetClass = String.class,
            fetch = FetchType.LAZY
    )
    @Getter
    protected Set<String> photos;
    
    @OneToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "discussion_id")
    protected Discussion discussion;
    
    public Card(String title) {
    
        setApproved(false);
        setTitle(title);
        photos = new HashSet<>();
    }
    
    public void addPhoto(String filename) {
        
        if(Objects.nonNull(filename) && !filename.isEmpty())
            photos.add(filename);
    }
    
    protected Double round(Double value) {
        
        return (double)(Math.round(value*100)/100);
    }
    
    public abstract Double getTotalRating();
    
    public abstract Integer getAssessorsCount();
    
    public abstract boolean containsAssessor(User user);
    
    public String getCardType() {
        
        return cardType.name();
    }
    
}

src/main/java/org/gab/estimateachers/entities/client/Dormitory.java
package org.gab.estimateachers.entities.client;

import lombok.Data;
import lombok.NoArgsConstructor;
import org.gab.estimateachers.entities.system.estimations.DormitoryEstimation;
import org.gab.estimateachers.entities.system.users.User;

import javax.persistence.*;
import java.util.List;
import java.util.stream.Collectors;

@Data
@NoArgsConstructor
@Entity
@Table(name = "dormitories")
public class Dormitory extends Card {
    
    @ManyToOne(
            cascade = CascadeType.ALL,
            fetch = FetchType.LAZY
    )
    @JoinTable(
            name = "university_dormitories",
            joinColumns = {@JoinColumn(name = "dormitory_id")},
            inverseJoinColumns = {@JoinColumn(name = "university_id")}
    )
    private University university;
    
    @OneToMany
    @JoinTable(
            name = "dormitories_estimations",
            joinColumns = @JoinColumn(name = "dormitory_id"),
            inverseJoinColumns = @JoinColumn(name = "estimation_id")
    )
    private List<DormitoryEstimation> estimations;
    
    public Double getCapacityRating() {
        
        return estimations.stream().map(DormitoryEstimation.class::cast).mapToDouble(DormitoryEstimation::getCapacityRating).average().orElse(0);
    }
    
    public Double getRoommatesRating() {
        
        return estimations.stream().map(DormitoryEstimation.class::cast).mapToDouble(DormitoryEstimation::getRoommatesRating).average().orElse(0);
    }
    
    public Double getCleaningRating() {
        
        return estimations.stream().map(DormitoryEstimation.class::cast).mapToDouble(DormitoryEstimation::getCleaningRating).average().orElse(0);
    }
    
    public Dormitory(String title, University university) {
        
        super(title);
        setUniversity(university);
        setCardType(CardType.DORMITORY);
    }
    
    public void estimation(DormitoryEstimation estimation) {
        
        estimations.add(estimation);
    }
    
    public Double getTotalRating() {
        
        return round(estimations.stream().mapToDouble(DormitoryEstimation::getTotalRating).average().orElse(0));
    }
    
    public Integer getAssessorsCount() {
        
        return estimations.size();
    }
    
    public boolean containsAssessor(User user) {
        
        return estimations.stream().map(DormitoryEstimation::getAssessor).collect(Collectors.toSet()).contains(user);
    }
}

src/main/java/org/gab/estimateachers/entities/client/Faculty.java
package org.gab.estimateachers.entities.client;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.gab.estimateachers.entities.system.estimations.FacultyEstimation;
import org.gab.estimateachers.entities.system.users.User;
import org.springframework.lang.NonNull;

import javax.persistence.*;
import java.util.HashSet;
import java.util.List;
import java.util.Objects;
import java.util.Set;
import java.util.stream.Collectors;

@NoArgsConstructor
@Entity
@Table(
        name = "faculties",
        uniqueConstraints = @UniqueConstraint(columnNames = {"title"})
)
@Getter
@Setter
public class Faculty extends Card {
    
    @ManyToOne(
            cascade = CascadeType.PERSIST,
            fetch = FetchType.LAZY
    )
    @NonNull
    @JoinTable(
            name = "university_faculties",
            joinColumns = {@JoinColumn(name = "faculty_id")},
            inverseJoinColumns = {@JoinColumn(name = "university_id")}
    )
    private University university;

    @ManyToMany(
            cascade = CascadeType.PERSIST,
            fetch = FetchType.LAZY
    )
    @JoinTable(
            name = "faculties_teachers",
            joinColumns = {@JoinColumn(name = "faculty_id")},
            inverseJoinColumns = {@JoinColumn(name = "teacher_id")}
    )
    private Set<Teacher> teachers;
    
    @OneToMany
    @JoinTable(
            name = "faculties_estimations",
            joinColumns = @JoinColumn(name = "faculty_id"),
            inverseJoinColumns = @JoinColumn(name = "estimation_id")
    
    )
    private List<FacultyEstimation> estimations;
    
    public Faculty(String title, University university) {
        
        setTitle(String.format("%s(%s)", title.substring(0, 1).toUpperCase().concat(title.substring(1)), university.getAbbreviation()));
        photos = new HashSet<>();
        setUniversity(university);
        setCardType(CardType.FACULTY);
    }
    
    public Double getPriceRating() {
        
        return estimations.stream().mapToDouble(FacultyEstimation::getPriceRating).average().orElse(0);
    }
    
    public Double getEducationRating() {
        
        return estimations.stream().mapToDouble(FacultyEstimation::getEducationRating).average().orElse(0);
    }
    
    public Double getTotalRating() {
        
        return estimations.stream().mapToDouble(FacultyEstimation::getTotalRating).average().orElse(0);
    }
    
    public Integer getAssessorsCount() {
        
        return estimations.size();
    }
    
    public boolean containsAssessor(User user) {
        
        return estimations.stream().map(FacultyEstimation::getAssessor).collect(Collectors.toSet()).contains(user);
    }
    
    public void estimation(FacultyEstimation estimation) {
        
        estimations.add(estimation);
    }
    
    public void addTeacher(Teacher teacher) {
    
        if(Objects.nonNull(teacher) && Objects.nonNull(teacher.getId()))
            teachers.add(teacher);
    }
}

src/main/java/org/gab/estimateachers/entities/system/applications/RequestType.java
package org.gab.estimateachers.entities.system.applications;

public enum RequestType {
    
    OPERATIONS_SERVICE, CHANGING_CARDS
    
}

src/main/java/org/gab/estimateachers/app/controllers/applications/ApplicationController.java
package org.gab.estimateachers.app.controllers.applications;

import lombok.extern.slf4j.Slf4j;
import org.gab.estimateachers.app.controllers.Errors.ControllerException;
import org.gab.estimateachers.app.services.*;
import org.gab.estimateachers.app.utilities.ApplicationsUtilities;
import org.gab.estimateachers.app.utilities.ListsUtilities;
import org.gab.estimateachers.entities.client.University;
import org.gab.estimateachers.entities.system.applications.CreatingCardApplication;
import org.gab.estimateachers.entities.system.applications.RegistrationApplication;
import org.gab.estimateachers.entities.system.applications.Request;
import org.gab.estimateachers.entities.system.applications.RequestType;
import org.gab.estimateachers.entities.system.users.User;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.HttpStatus;
import org.springframework.retry.annotation.Backoff;
import org.springframework.retry.annotation.Recover;
import org.springframework.retry.annotation.Retryable;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.servlet.ModelAndView;

import javax.servlet.http.HttpServletRequest;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;

@Slf4j
@Controller
@PreAuthorize("hasAuthority('ADMIN')")
@RequestMapping("/applications")
public class ApplicationController {
    
    @Autowired
    @Qualifier("applicationsUtilities")
    private ApplicationsUtilities applicationsUtilities;
    
    @Autowired
    @Qualifier("listsUtilities")
    private ListsUtilities listUtilities;
    
    @Autowired
    @Qualifier("registrationApplicationService")
    private RegistrationApplicationService registrationApplicationService;
    
    @Autowired
    @Qualifier("creatingCardApplicationService")
    private CreatingCardApplicationService creatingCardApplicationService;
    
    @Autowired
    @Qualifier("requestService")
    private RequestService requestService;
    
    @Autowired
    @Qualifier("universityService")
    private UniversityService universityService;
    
    @Autowired
    @Qualifier("teacherService")
    private TeacherService teacherService;
    
    @Autowired
    @Qualifier("facultyService")
    private FacultyService facultyService;
    
    @Autowired
    @Qualifier("dormitoryService")
    private DormitoryService dormitoryService;
    
    @GetMapping(value = {
            "/requests/reject/{id}",
            "/requests/success/{id}",
            "/reject/card/{id}",
            "/reject/registry/{id}"
    })
    @Retryable(maxAttempts = 5, value = ControllerException.class, backoff = @Backoff(delay = 300, multiplier = 1.5))
    public String plug(HttpServletRequest request) {
      
        String header = request.getHeader("Referer");
        
        log.info("A plug has triggered in applications controller, the request has been redirected to: " + header);
        
        return "redirect:" + header;
    }
    
    @GetMapping("/users")
    @Retryable(maxAttempts = 5, value = ControllerException.class, backoff = @Backoff(delay = 300, multiplier = 1.5))
    public String newUserApplications(Model model) {
        
        model.addAttribute("applications", listUtilities.getRegistrationApplicationList());
        model.addAttribute("type", "registry");
        
        log.info("Logged in to the page with registration applications");
        
        return "/applications";
    }
    
    @GetMapping("/cards")
    @Retryable(maxAttempts = 5, value = ControllerException.class, backoff = @Backoff(delay = 300, multiplier = 1.5))
    public String newCardApplications(Model model) {
        
        model.addAttribute("applications", listUtilities.getCreatingCardApplicationList());
        model.addAttribute("type", "card");
    
        log.info("Logged in to the page with applications for creating cards");
        
        return "/applications";
    }
    
    @GetMapping("/approving/{id}")
    @Retryable(maxAttempts = 5, value = ControllerException.class, backoff = @Backoff(delay = 300, multiplier = 1.5))
    public String approvingCard(@PathVariable(name = "id") Long applicationId,
                                Model model) {
    
        CreatingCardApplication application = creatingCardApplicationService.findById(applicationId);
        
        if(application.isViewed()) {
            
            model.addAttribute("application", application);
            
            log.info("The admin requested access to the application, which is already being considered");
            
            return "/application_is_viewed";
        }
        
        application.setViewed(true);
        creatingCardApplicationService.save(application);
        Long cardId = application.getCardId();
        
        switch (application.getCardType()) {
            
            case UNIVERSITY -> model.addAttribute("card", universityService.findById(cardId));
            case DORMITORY -> model.addAttribute("card", dormitoryService.findById(cardId));
            case TEACHER -> model.addAttribute("card", teacherService.findById(cardId));
            case FACULTY -> model.addAttribute("card", facultyService.findById(cardId));
        }
        
        model.addAttribute("cardType", application.getCardType().toString());
        model.addAttribute("application", application);
        
        log.info("The admin requested access to the application");
        
        return "/processing_new_card";
    }
    
    @PostMapping("/approving")
    @Retryable(maxAttempts = 5, value = ControllerException.class, backoff = @Backoff(delay = 300, multiplier = 1.5))
    public String approvingCardSave(@RequestParam(name = "id") Long applicationId,
                                Model model) {
        
        creatingCardApplicationService.approve(applicationId);
        
        log.info("The admin approved application for creating cards");
        
        return "redirect:/applications/cards";
    }
    
    @GetMapping("/processing/first/{id}")
    @Retryable(maxAttempts = 5, value = ControllerException.class, backoff = @Backoff(delay = 300, multiplier = 1.5))
    public String processingApplicationFirstStep(@PathVariable(name = "id") Long applicationId,
                                                 Model model) {
            
        RegistrationApplication application = registrationApplicationService.findById(applicationId);
        
        if(application.isViewed()) {
            
            model.addAttribute("application", application);
    
            log.info("The admin requested access to the application, which is already being considered");
            
            return "/application_is_viewed";
        }
        
        application.setViewed(true);
        registrationApplicationService.save(application);
        model.addAttribute("universities", listUtilities.getUniversitiesAbbreviationsList());
        model.addAttribute("application", application);
        model.addAttribute("student", application.getStudent());
        
        log.info("The admin has started viewing the application");
        
        return "/process_application_first";
    }
    
    @PostMapping("/processing/first/{id}")
    @Retryable(maxAttempts = 5, value = ControllerException.class, backoff = @Backoff(delay = 300, multiplier = 1.5))
    public String processingApplicationFirstStepSave(@PathVariable(name = "id") Long applicationId,
                                                     @RequestParam("course") Integer course,
                                                     @RequestParam("university") String abbreviationUniversity,
                                                     Model model) {
        
        University university = universityService.findByAbbreviation(abbreviationUniversity);
        model.addAttribute("dormitories", listUtilities.convertToTitlesList(university.getDormitories()));
        model.addAttribute("faculties", listUtilities.convertToTitlesList(university.getFaculties()));
        model.addAttribute("university", university);
        model.addAttribute("course", course);
        
        log.info("The admin save first step the application viewing");
        
        return processingApplicationSecondStep(applicationId, model);
    }
    
    @GetMapping("/processing/second/{id}")
    @Retryable(maxAttempts = 5, value = ControllerException.class, backoff = @Backoff(delay = 300, multiplier = 1.5))
    public String processingApplicationSecondStep(@PathVariable(name = "id") Long applicationId,
                                                  Model model) {
        
        RegistrationApplication application = registrationApplicationService.findById(applicationId);
        
        model.addAttribute("application", application);
        model.addAttribute("student", application.getStudent());
    
        log.info("The admin started second step the application viewing");
        
        return "/process_application_second";
    }
    
    @PostMapping("/processing/second/{id}")
    @Retryable(maxAttempts = 5, value = ControllerException.class, backoff = @Backoff(delay = 300, multiplier = 1.5))
    public String processingApplicationSecondStepSave(@PathVariable(name = "id") Long applicationId,
                                                      @RequestParam("faculty") String facultyTitle,
                                                      @RequestParam("universityId") Long universityId,

src/main/resources/templates/add_admin.ftl
<#import "parts/main.ftl" as main>
<#import "parts/users_logic.ftl" as ul>
<#import "parts/security.ftl" as security>

<@main.page>

<div class="mt-2">
    <form method = "post">
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Login: </label>
            <div class="col-sm-6">
                <input type = "text" name = "username" id = "username" placeholder = "Your login" class="form-control" />
                <div id="loginHelpBlock" class="form-text">
                    The login must consist of 2-32 letters
                </div>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Password: </label>
            <div class="col-sm-6">
                <input type = "password" name = "password" id = "password" placeholder = "Your password" class="form-control"/>
            </div>
        </div>
        <@security.token />
        <button type = "submit" class="btn btn-primary">Add new admin</button>
    </form>
</div>
<div class="row mt-2">
    <#if remarks??>
        <@ul.foreach collection = remarks![] status="danger" />
    </#if>
</div>


</@main.page>

src/main/resources/templates/applications.ftl
<#import "parts/main.ftl" as main>
<#import "parts/users_logic.ftl" as ul>

<@main.page>

    <h2><span>Applications:</span></h2>

    <#if applications??>

        <#list applications as application>
            <div class="card">
                <div class="card-header">
                    Application №${application.id}
                </div>`
                <div class="card-body">
                    <h5 class="card-title"><i>Date sending: <#if application.date??>${application.date}<#else>None</#if></i></h5>
                    <#if type="registry">
                        <a href="/applications/processing/first/${application.id}" class="btn btn-primary">Reject</a>
                    <#elseif type="card">
                        <a href="/applications/approving/${application.id}" class="btn btn-primary">Reject</a>
                    <#elseif type="request">
                        <a href="/applications/requests/${application.id}" class="btn btn-primary">Reject</a>
                    </#if>
                </div>
            </div>
        </#list>

    </#if>

</@main.page>

src/main/resources/templates/confirm_result.ftl
<#import "parts/main.ftl" as main>

<@main.page>

    <div class="alert alert-${status}" role="alert">
        ${text}
    </div>

</@main.page>

src/main/resources/templates/discussion.ftl
<#import "parts/main.ftl" as main>
<#import "parts/security.ftl" as security>
<#import "parts/users_logic.ftl" as ul>
<#import "parts/cards_logic.ftl" as cl>
<#import "parts/discussion_logic.ftl" as dl>

<@main.page>
    <div class="row">
        <div class="col ml-12 mt-5 sticky-top">

            <h2><span>${discussion.title}</span></h2>
        </div>
        <div class="col-3 w-80 ml-12 mt-5 sticky-top" style="position: fixed; top: 150px; right: 20px;">
            <form class="d-flex w-30" method="post" action="/discussions/comment/search/text">
                <input class="form-control me-2" value="${text!''}" name="text" type="search" placeholder="Comment's text" aria-label="Search">
                <input type="hidden" name="discussionId" value="${discussion.id}" />
                <button class="btn btn-outline-success" type="submit">Search</button>
                <@security.token />
            </form>
            <form class="d-flex w-30" method="post" action="/discussions/comment/search/author">
                <input class="form-control me-2" value="${username!''}" name="username" type="search" placeholder="Comment's author nick" aria-label="Search">
                <input type="hidden" name="discussionId" value="${discussion.id}" />
                <button class="btn btn-outline-primary" type="submit">Search</button>
                <@security.token />
            </form>
        </div>
        <div class="col-3 w-80 ml-12 mt-5 sticky-top" style="position: fixed; top: 150px; left: 20px;">
            <form class="d-flex w-30" method="get" action="/discussions/sorted/asc/${discussion.id}">
                <button class="btn btn-danger" type="submit"> &#11015; Get seconds first with a low rating</button>
                <@security.token />
            </form>
            <form class="d-flex w-30" method="get" action="/discussions/sorted/desc/${discussion.id}">
                <button class="btn btn-success" type="submit"> &#11014; Get seconds first with a high rating</button>
                <@security.token />
            </form>
            <form class="d-flex w-30" method="get" action="/discussions/get/${discussion.id}">
                <button class="btn btn-secondary" type="submit"> &#9719; By date sending</button>
                <@security.token />
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col mt-3 ml-5 w-80 fixed-right">
            <#if comments??>
                <#if comments?has_content>
                    <#list comments as comment>
                        <div class="row mt-2">
                            <@dl.comment_view comment=comment />
                        </div>
                    </#list>
                </#if>
            </#if>
        </div>
        <div class="col-3 w-80" style="position: fixed; bottom: 10px; right: 20px;">
            <@dl.comment_send />
        </div>
    </div>
</@main.page>

src/main/resources/templates/dormitory_card.ftl
<#import "parts/main.ftl" as main>
<#import "parts/cards_logic.ftl" as cl>
<#import "parts/users_logic.ftl" as ul>
<#import "parts/security.ftl" as security>

<@main.page>

<div class="row mt-3">
    <div class="col-3">
        <@cl.title card=dormitory type="dormitory" />
    </div>
    <div class="col-2 mt-5">

        <form method="post" action="/cards/collection/add">
            <input type="hidden" value="${dormitory.id}" name="cardId" />
            <input type="hidden" value="${dormitory.getCardType()}" name="cardType" />
            <input type="hidden" value="${inCollection?c}" name="inCollection" />
            <@security.token />
            <button class="btn btn-primary" type="submit">
                <#if inCollection??>
                <#if inCollection><i class="fa fa-close"></i><#else><i class="fa fa-folder"></i></#if>
                <#else>
                <i class="fa fa-folder"></i>
            </#if>
            </button>
        </form>
    </div>
</div>
</div>

<div class="row mt-5">
    <@cl.images number=0 photos=dormitory.photos size=dormitory.photos?size />
</div>
<div class="row mt-5">
    <div class="col-3 w-60">
        <ul class="list-group">
            <li class="list-group-item">Cleaning: ${dormitory.cleaningRating}/10</li>
            <li class="list-group-item">Roommates: ${dormitory.roommatesRating}/10</li>
            <li class="list-group-item">Capacity: ${dormitory.capacityRating}/10</li>
            <li class="list-group-item">Rating: ${dormitory.totalRating}/10</li>
        </ul>

        <div class="modal fade" id="estimationModal" aria-hidden="true" aria-labelledby="estimationModalLabel" tabindex="-1">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="estimationModalLabel">Your estimation</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <div class="form group">
                            <form method="post" action="/cards/estimation/dormitory">
                                <@cl.estimation title="Cleaning rating" name="cleaningRating" />
                                <@cl.estimation title="Roommates rating" name="roommatesRating" />
                                <@cl.estimation title="Capacity rating" name="capacityRating" />
                                <input type="hidden" value="${dormitory.id}" name="cardId" />
                                <@security.token />
                                <button class="btn-primary" type="submit">Estimate</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
<#if !estimated && !isAdmin>
    <a class="btn btn-primary mt-2" data-bs-toggle="modal" href="#estimationModal" role="button">Estimate this card</a>
</#if>

    <form class="mt-2" method = "get" action = "/discussions/get/${dormitory.discussion.id}">
        <button class="btn btn-secondary" type="submit">To discussion...</button>
    </form>
<div class="row mt-3">
    University:
    <form method = "get" action = "/cards/get">
        <input type="hidden" name = "cardType" value = "${dormitory.university.getCardType()}" />
        <input type="hidden" name = "id" value = ${dormitory.university.id} />
        <button class="btn btn-second" type="submit"> ${dormitory.university.title}</button>
    </form>
</div>
</@main.page>

src/main/resources/templates/faculty_card.ftl
<#import "parts/main.ftl" as main>
<#import "parts/cards_logic.ftl" as cl>
<#import "parts/users_logic.ftl" as ul>
<#import "parts/security.ftl" as security>

<@main.page>

<div class="row mt-3">
    <div class="col-3">
        <@cl.title card=faculty type="faculty" />
    </div>
    <div class="col-2 mt-5">

        <form method="post" action="/cards/collection/add">
            <input type="hidden" value="${faculty.id}" name="cardId" />
            <input type="hidden" value="${faculty.getCardType()}" name="cardType" />
            <input type="hidden" value="${inCollection?c}" name="inCollection" />
            <@security.token />
            <button class="btn btn-primary" type="submit">
                <#if inCollection??>
                <#if inCollection><i class="fa fa-close"></i><#else><i class="fa fa-folder"></i></#if>
                <#else>
                <i class="fa fa-folder"></i>
            </#if>
            </button>
        </form>
    </div>
</div>
</div>

<div class="row mt-5">
    <@cl.images number=0 photos=faculty.photos size=faculty.photos?size />
</div>
<div class="row mt-5">
    <div class="col-3 w-60">
        <ul class="list-group">
            <li class="list-group-item">Price: ${faculty.priceRating}/10</li>
            <li class="list-group-item">Education: ${faculty.educationRating}/10</li>
            <li class="list-group-item">Rating: ${faculty.totalRating}/10</li>
        </ul>

        <div class="modal fade" id="estimationModal" aria-hidden="true" aria-labelledby="estimationModalLabel" tabindex="-1">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="estimationModalLabel">Your estimation</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <div class="form group">
                            <form method="post" action="/cards/estimation/faculty">
                                <@cl.estimation title="Education rating" name="educationRating" />
                                <@cl.estimation title="Price rating" name="priceRating" />
                                <input type="hidden" value="${faculty.id}" name="cardId" />
                                <@security.token />
                                <button class="btn-primary" type="submit">Estimate</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <#if !estimated && !isAdmin>
            <a class="btn btn-primary mt-2" data-bs-toggle="modal" href="#estimationModal" role="button">Estimate this card</a>
        </#if>
    <form class="mt-2" method = "get" action = "/discussions/get/${faculty.discussion.id}">
        <button class="btn btn-secondary" type="submit">To discussion...</button>
    </form>
    </div>
</div>
<div class="row mt-3">
    <div class="col-4">
        <h5>University:</h5>
        <form method = "get" action = "/cards/get">
            <input type="hidden" name = "cardType" value = "${faculty.university.getCardType()}" />
            <input type="hidden" name = "id" value = ${faculty.university.id} />
            <button class="btn" type="submit">${faculty.university.title}</button>
        </form>
    </div>
</div>
<div class="row mt-3">
    <div class="col-4">
        <h5>Teachers:</h5>
        <@cl.links cards=faculty.teachers />
    </div>
</div>
</@main.page>

src/main/resources/templates/login.ftl
<#import "parts/main.ftl" as main>
<#import "parts/users_logic.ftl" as ul>

<@main.page>

    <@ul.data_form registry = false textButton = "Sign in" />


    <#if remarks??>
        <@ul.foreach collection = remarks![] status="danger"/>
    </#if>

</@main.page>